eta: 0.01
n_iter: 1000
lambda_: 0.01
gradient_type: "mini-batch"  # "batch" ou "sgd", "mini-batch"
batch_size: 50  # seulement pour mini-batch
early_stopping: true  # Active Early Stopping
patience: 10  # Nombre d'itérations sans amélioration avant l'arrêt
tolerance: 1e-4  # Seuil de tolérance pour l'amélioration du coût
